apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-a
spec:
  replicas: 8 # para simular um deploy canario
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        version: A
    spec:
      containers:
        - name: webapp
          image: robertocamara/webapp-kubernetes:v5.5A
          resources:
            limits:
              memory: "20Mi"
              cpu: "50m"
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-b
spec:
  replicas: 2 # para simular um deploy canario
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        version: B
    spec:
      containers:
        - name: webapp
          image: robertocamara/webapp-kubernetes:v5.5B
          resources:
            limits:
              memory: "20Mi"
              cpu: "50m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: webapp # filtro para identificar os deployments
  ports:
  - port: 8000 # porta definida no k3s
    targetPort: 80 # porta dos containers
    nodePort: 30000 # ao acessar a porta 8000 do host local será redirecionado para a porta 30000 do service
            

