apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule # IMPORTANTE: posso ter um destinarionrule sem ter um virtualservice, caso não existe, o destinationrule segue o padrão do kubernetes
metadata:
  name: webapp-istio-dr
spec:
  host: webapp-istio-service # são os services do kubernetes
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN # esse é o padrão
  subsets:
  - name: v1
    labels:
      version: A # mesma label-version que foi definida no deployment
    trafficPolicy: # definindo um loadbalancer específico pro subset
      loadBalancer:
        simple: LEAST_CONN 
  - name: v2
    labels:
      version: B # mesma label-version que foi definida no deployment