apiVersion: apps/v1 
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:  
  selector:
    matchLabels:
      app: webapp
  replicas: 10
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: robertocamara/webapp-kubernetes:v2
