apiVersion: v1
kind: Service
metadata:
  name: mysql-h # este nome deve ser exatamente o nome que foi definido na tag "serviceName" do arquivo de configuração do statefulset
spec:
  selector: # utilizado para filtrar e selecionar os os apps definidos no mathLabels
    app: mysql 
  ports:
    - port: 3306
  clusterIP: None # service entende que não vai trabalhar com ip e sim com resolução de nome (DNS)
  
