apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector: # utilizado para filtrar e selecionar os os apps definidos no mathLabels
    app: webapp
  type: LoadBalancer # ClusterIP, NodePort
  ports:
  - name: webapp-service
    port: 80
    protocol: TCP
